sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: PV9RKWzrVzIMvl7Qfh+Mqfq+E3Xiw/Pv2J40W9Hk4TaoRXjMYUBx4L6tSa3+U8LC+WHVc+0QpjlQUPTIgZ3zJiagHmXWpf7LCdne+8BocnG+gBfD1HUZjiX8wxaHOV0WdWvleMc/R2IvP6l2vk6U+CXu+ajyar2T/VYJfVzzUizp60op2peH0LGwLy0p8Pv1TVFLkJHPJDm9JTDQEq6Bic5S5M2b9LN+BfMX3wvUsNlJeGeAX8q9yNV9EG9/m8yfHcGFIBPGlj98YQ62oEZAo+ljGSOPMN7rqIpSVjP54PGZTi2KJWxr9Z0yqEFVk9+PkQW2KqJs0vZzmn+BSDZBFmeaB0CPx6i4M9OFY+56uiWP9BhNlPioV3k7Y10EsItNRUAh6CUg1kJZdC3s34xpqjUNzDZqWJT0LD//DtN3Bku7+Y6zeL5J8mld91Q+SdvZdarD24h6YlH2njchl4RV3FjFCI/y+b2pklmgIEn0zfx+5DaiPp8g24ci/8u5oOchLUuYgWKEL3GOrENWqvwKgqSVyC4hODJnh6ITzWN06/0tWHof64H6IsoXga+fbYlO9N8VSPVVW8/LOTr/p4Jq/EybSkzvhCuOFD1vLvsR6r5KiHBpwMEtETweqGVS7kZXwWIuz7R3NeP9hQef1YlKh4Do3Rt2VWDoFWq37R4jYfQ=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Biographia-Literaria_6081
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy